//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class PlayerController : Controller
	{
		private void North()
		{
		}

		private void East()
		{
		}
		private void South()
		{
		}
		private void West()
		{
		}
		
		private void Use()
		{
		}
		private void Fire()
		{
		}
		private void Item()
		{
		}
		
		private void Select(){
		}

		public PlayerController ()
		{

		}
	}
}

